Repository d3b-center/OpenPedCan-analysis, pull requests merged in 2021-08, with the labels that each got.

#73 Update OpenPedCan-analysis README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: ready for review

#71 [Update annotator for v7 Part 3] Add GTEx tissue UBERON annotation columns
  analyses/README.md
  analyses/long-format-table-utils/README.md
  analyses/long-format-table-utils/annotator/annotator-api.R
  analyses/long-format-table-utils/annotator/annotator-cli.R
  analyses/long-format-table-utils/annotator/download-annotation-data.R
  analyses/long-format-table-utils/annotator/tests/test_annotate_long_format_table.R
  analyses/long-format-table-utils/annotator/tests/test_annotator_cli.R
  analyses/long-format-table-utils/annotator/tests/test_data/v7_inspected_annotated_test_long_format_table.tsv
  analyses/long-format-table-utils/annotator/tests/test_data/v7_test_long_format_table.tsv
Labels: ready for review

#29 Expression plots/tables: tumors only and tumor vs normal
  Dockerfile
  analyses/README.md
  analyses/tumor-gtex-plots/.gitignore
  analyses/tumor-gtex-plots/01-tumor-gtex-plots.R
  analyses/tumor-gtex-plots/02-chunkwise-annotate-and-zip.R
  analyses/tumor-gtex-plots/README.md
  analyses/tumor-gtex-plots/run-annotator.sh
  analyses/tumor-gtex-plots/run-pan-cancer-plots.sh
  analyses/tumor-gtex-plots/run-tumor-gtex-plots.sh
  analyses/tumor-gtex-plots/run-tumor-normal-gtex-plots.sh
  analyses/tumor-gtex-plots/util/pan_cancer_plot.R
  analyses/tumor-gtex-plots/util/pubTheme.R
  analyses/tumor-gtex-plots/util/tumor_normal_gtex_plot.R
Labels: merge next

#82 Update Dockerfile to install Python package `openpyxl`
  Dockerfile
Labels: ready for review

#87 Focal-CN Module: change each sample workflow back to group workflow
  analyses/focal-cn-file-preparation/04-prepare-cn-file.R
Labels: ready for review, data-release

#81 Focal CN Merge File Script
  analyses/focal-cn-file-preparation/07-consensus-annotated-merge.R
  analyses/focal-cn-file-preparation/README.md
  analyses/focal-cn-file-preparation/run-prepare-cn-OpenTarget.sh
Labels: ready for review, data-release

#90 Independent Sample Rerun with v8
  analyses/independent-samples/00-repeated-samples.nb.html
  analyses/independent-samples/01-generate-independent-specimens.R
  analyses/independent-samples/02-generate-independent-rnaseq.R
  analyses/independent-samples/03-qc-independent-samples.nb.html
  analyses/independent-samples/results/independent-specimens.rnaseq.primary-plus.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.primary-plus.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.primary.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.primary.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.relapse.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.relapse.tsv
  analyses/independent-samples/results/independent-specimens.wgs.primary-plus.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgs.primary-plus.tsv
  analyses/independent-samples/results/independent-specimens.wgs.primary.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgs.primary.tsv
  analyses/independent-samples/results/independent-specimens.wgs.relapse.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgs.relapse.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.primary-plus.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.primary-plus.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.primary.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.primary.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.relapse.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.relapse.tsv
Labels: data-release

#93 Update `long-format-table-utils/annotator` for v8 data release
  analyses/long-format-table-utils/README.md
  analyses/long-format-table-utils/annotator/annotation-data/ensg-gene-full-name-refseq-protein.tsv
  analyses/long-format-table-utils/annotator/annotator-api.R
  analyses/long-format-table-utils/annotator/download-annotation-data.R
Labels: ready for review, merge next

#97 Update S3 bucket path
  download-data.sh
Labels: merge next

#83 Generate an Excel spreadsheet for PedOT website table display orders and names
  analyses/README.md
  analyses/pedot-table-column-display-order-name/.flake8
  analyses/pedot-table-column-display-order-name/01-generate-pedot-column-display-order-name-xlsx.py
  analyses/pedot-table-column-display-order-name/README.md
  analyses/pedot-table-column-display-order-name/docs/pedot_table_display_column_order_name_coordination_Aug5_2021_v1.2.png
  analyses/pedot-table-column-display-order-name/results/pedot-table-column-display-order-name.xlsx
  analyses/pedot-table-column-display-order-name/run-pedot-table-column-display-order-name.sh
  analyses/pedot-table-column-display-order-name/utils/__init__.py
  analyses/pedot-table-column-display-order-name/utils/tsv.py
  analyses/pedot-table-column-display-order-name/utils/xlsx.py
Labels: ready for review, merge next, high priority
