Repository d3b-center/OpenPedCan-analysis, pull requests merged in 2021-09, with the labels that each got.

#99 Adding updated codes for EFO and MONDO,with comments
  analyses/efo-mondo-mapping/input/EFO_MONDO_mapping_review.txt
  analyses/efo-mondo-mapping/results/efo-mondo-map.tsv
Labels: merge next

#96 Fusion Frequency Table Update
  analyses/fusion-frequencies/01-fusion-frequencies.R
  analyses/fusion-frequencies/README.md
  analyses/fusion-frequencies/results/putative-oncogene-fused-gene-freq.jsonl.gz
  analyses/fusion-frequencies/results/putative-oncogene-fused-gene-freq.tsv.gz
  analyses/fusion-frequencies/results/putative-oncogene-fusion-freq.jsonl.gz
  analyses/fusion-frequencies/results/putative-oncogene-fusion-freq.tsv.gz
  analyses/fusion-frequencies/run-frequencies.sh
Labels: ready for review, high priority

#95 Update focal cn file preparation
  analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.Rmd
  analyses/focal-cn-file-preparation/01-add-ploidy-cnvkit.nb.html
  analyses/focal-cn-file-preparation/README.md
Labels: merge next, high priority

#84 Tp53 nf1 update Part 1
  analyses/tp53_nf1_score/00-tp53-nf1-alterations.R
  analyses/tp53_nf1_score/01-apply-classifier.py
  analyses/tp53_nf1_score/02-qc-rna_expression_score.Rmd
  analyses/tp53_nf1_score/02-qc-rna_expression_score.nb.html
  analyses/tp53_nf1_score/03-evaluate-classifier.py
  analyses/tp53_nf1_score/README.md
  analyses/tp53_nf1_score/results/TP53_NF1_snv_alteration.tsv
  analyses/tp53_nf1_score/results/gene-expression-rsem-tpm-collapsed_classifier_scores.tsv
  analyses/tp53_nf1_score/results/pbta-gene-expression-rsem-fpkm-collapsed.polya_classifier_scores.tsv
  analyses/tp53_nf1_score/results/pbta-gene-expression-rsem-fpkm-collapsed.stranded_classifier_scores.tsv
  analyses/tp53_nf1_score/run_classifier.sh
Labels: ready for review
