Repository d3b-center/OpenPedCan-analysis, pull requests merged in 2021-07, with the labels that each got.

#34 Part 3 v6 release: Update download script and doc
  doc/data-files-description.md
  doc/data-formats.md
  doc/release-notes.md
  download-data.sh
Labels: data-release, ready for review

#48 Independent Samples Analyses Updated
  analyses/independent-samples/00-repeated-samples.Rmd
  analyses/independent-samples/00-repeated-samples.nb.html
  analyses/independent-samples/01-generate-independent-specimens.R
  analyses/independent-samples/02-generate-independent-rnaseq.R
  analyses/independent-samples/README.md
  analyses/independent-samples/independent-samples.R
  analyses/independent-samples/independent_rna_samples.R
  analyses/independent-samples/results/independent-specimens.rnaseq.primary-plus.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.primary-plus.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.primary.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.primary.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.relapse.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.rnaseq.relapse.tsv
  analyses/independent-samples/results/independent-specimens.wgs.primary-plus.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgs.primary.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgs.relapse.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.primary-plus.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.primary-plus.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.primary.eachcohort.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.primary.tsv
  analyses/independent-samples/results/independent-specimens.wgswxspanel.relapse.eachcohort.tsv
  analyses/independent-samples/run-independent-samples.sh
Labels: merge next

#37 Fusion Filtering Stagger PR2
  analyses/fusion_filtering/00-normal-matrix-generation.R
  analyses/fusion_filtering/01-fusion-standardization.R
  analyses/fusion_filtering/02-fusion-filtering.R
  analyses/fusion_filtering/run_fusion_merged.sh
Labels: merge next

#38 Fusion filtering staggered PR3
  analyses/fusion_filtering/00-normal-matrix-generation.R
  analyses/fusion_filtering/03-Calc-zscore-annotate.R
  analyses/fusion_filtering/run_fusion_merged.sh
Labels: merge next

#40 Fusion filtering staggered PR5
  analyses/fusion_filtering/00-normal-matrix-generation.R
  analyses/fusion_filtering/05-QC_putative_onco_fusion_distribution.Rmd
  analyses/fusion_filtering/05-QC_putative_onco_fusion_distribution.nb.html
  analyses/fusion_filtering/results/fusion-putative-oncogenic.tsv
  analyses/fusion_filtering/results/pbta-fusion-putative-oncogenic.tsv
Labels: merge next

#61 release v7
  doc/data-files-description.md
  doc/release-notes.md
  download-data.sh
Labels: merge next

#66 [Update annotator for v7 Part 1] change `ensg-hugo-rmtl-v1-mapping.tsv` to `ensg-hugo-rmtl-mapping.tsv`
  analyses/long-format-table-utils/README.md
  analyses/long-format-table-utils/annotator/annotator-api.R
  analyses/long-format-table-utils/annotator/tests/test_data/inspected_annotated_test_long_format_table.tsv
Labels: merge next

#69 [Update annotator for v7 Part 2] Only require columns that need to be joined by
  analyses/long-format-table-utils/README.md
  analyses/long-format-table-utils/annotator/annotator-api.R
  analyses/long-format-table-utils/annotator/tests/test_annotate_long_format_table.R
  analyses/long-format-table-utils/annotator/tests/test_annotator_cli.R
Labels: merge next

#64 [Update `rna-seq-expression-summary-stats` module for v7 Part 1] use `annotator` API
  analyses/rna-seq-expression-summary-stats/01-tpm-summary-stats.R
  analyses/rna-seq-expression-summary-stats/README.md
  analyses/rna-seq-expression-summary-stats/run-tests.sh
  analyses/rna-seq-expression-summary-stats/tests/helper_import_function.R
  analyses/rna-seq-expression-summary-stats/tests/test_data/test_import_function_empty.R
  analyses/rna-seq-expression-summary-stats/tests/test_data/test_import_function_non_empty.R
  analyses/rna-seq-expression-summary-stats/tests/test_format_cohort_sample_counts.R
  analyses/rna-seq-expression-summary-stats/tests/test_helper_import_function.R
Labels: ready for review
