Repository d3b-center/OpenPedCan-analysis, pull requests merged in 2022-08, with the labels that each got.

#223 Update analysis modules README
  analyses/README.md
Labels: ready for review, high priority

#234 update ubuntu version
  .github/workflows/run-analysis.yml
  Dockerfile
Labels: merge next

#237 Use buildx layer caching on analysis workflow
  .github/workflows/build-and-push-docker.yml
  .github/workflows/build-docker.yml
  .github/workflows/run-analysis.yml
  action.yml
Labels: work in progress

#244 script to generate mtp tables
  Dockerfile
  scripts/generate-mtp-tables.sh
Labels: work in progress
